import express from "express";
import Groq from "groq-sdk";
import path from "node:path";
import { fileURLToPath } from "node:url";
const __filename=fileURLToPath(import.meta.url),__dirname=path.dirname(__filename);const app=express();const port=process.env.PORT||3000;const model=process.env.GROQ_MODEL||"openai/gpt-oss-120b";
app.use(express.json({limit:"1mb"}));app.use(express.static(path.join(__dirname,"public")));
const systemPrompt=`You are NTEK eBay Customer Support AI for a UK eBay seller of household and everyday products. Write natural, polite, concise buyer-facing replies in UK English. Never invent tracking, delivery dates, refunds, stock, guarantees or policies. Use only buyer/seller facts supplied. If facts are missing, ask for confirmation or the necessary information. Never mention being an AI. De-escalate complaints. Do not promise an outcome the seller has not confirmed. Return only the ready-to-send reply.`;
function client(){return process.env.GROQ_API_KEY?new Groq({apiKey:process.env.GROQ_API_KEY}):null}
app.get("/api/health",(_q,r)=>r.json({ok:true,provider:"Groq",model,configured:!!process.env.GROQ_API_KEY}));
app.post("/api/reply",async(req,res)=>{try{const c=client();if(!c)return res.status(500).json({error:"GROQ_API_KEY is not configured on the server."});const {buyerMessage,context="",tone="friendly and professional",length="normal",settings={},productInfo=""}=req.body||{};if(!buyerMessage?.trim())return res.status(400).json({error:"Please provide a buyer message."});const user=`Create an eBay buyer reply. Tone: ${tone}. Length: ${length}.\nStore: ${settings.store||"NTEK"}\nDefault signature: ${settings.signature||""}\nSeller instructions: ${settings.instructions||""}\nProduct information: ${productInfo||""}\nSeller/order context: ${context||"No additional context."}\nBuyer message:\n${buyerMessage.trim()}`;const x=await c.chat.completions.create({model,messages:[{role:"system",content:systemPrompt},{role:"user",content:user}],temperature:.55,max_completion_tokens:700});const reply=x.choices?.[0]?.message?.content?.trim();if(!reply)return res.status(502).json({error:"The AI returned an empty response."});res.json({reply,model})}catch(e){console.error(e);res.status(e?.status||500).json({error:e?.error?.error?.message||e?.message||"AI request failed."})}});
app.get("*",(_q,r)=>r.sendFile(path.join(__dirname,"public","index.html")));app.listen(port,()=>console.log(`NTEK Support AI running on port ${port}`));